### ISSUE TITLE
Make a way of loading a lua class?

### ISSUE THREAD

**Issue by hughperkins** [soumith/torch.js#2]
These 80 lines of code https://github.com/hughperkins/pytorch/blob/master/src/PyTorchAug.py#L186-L252 are more or less sufficient to making a lua class look like a python class.  Maybe can do the same thing in javascript???  Everyone is always asking for python, but nodejs is popular too.  A high-performance javascript gpu library sounds like not a bad way forward :-)

**Comment by hughperkins** [comment]
Seems javascript doesnt have 'magic methods', like python does.  However, there are [direct proxies](http://wiki.ecmascript.org/doku.php?id=harmony:direct_proxies) apparently, that can be [enabled in nodejs with --harmony-proxies](http://stackoverflow.com/questions/10665892/enable-harmony-proxies-in-nodejs/10666902#10666902), maybe.

**Comment by soumith** [comment]
oh, i did not think of doing this. since this whole framework was a one-time hack i did, i didn't think too much into it.
